{
    "name": "oslllo-validator-exception",
    "version": "1.0.2",
    "description": "All in one Javascript validator but throws an exception on false",
    "main": "src/index.js",
    "scripts": {
        "test": "npm run build && nyc mocha && npm run lint",
        "eslint": "node_modules/.bin/eslint",
        "lint": "npm run eslint -- src test",
        "webpack": "node_modules/.bin/webpack",
        "build": "npm run browser:build",
        "browser:build": "npm run browser:build.prod && npm run browser:build.dev",
        "browser:build.dev": "npm run webpack -- --config webpack.dev.js",
        "browser:build.prod": "npm run webpack -- --config webpack.prod.js",
        "coverage": "nyc report --reporter=text-lcov | coveralls"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/oslllo/validator-exception.git"
    },
    "author": "",
    "license": "MIT",
    "files": [
        "src",
        "dist",
        "LICENCE",
        "README.md"
    ],
    "bugs": {
        "url": "https://github.com/oslllo/validator-exception/issues"
    },
    "homepage": "https://docs.oslllo.com/validator/master",
    "dependencies": {
        "oslllo-validator": "^1.1.0"
    },
    "keywords": [
        "oslllo",
        "validator",
        "validator-exception",
        "exception",
        "javascript",
        "all-in-one-validator",
        "all-in-one"
    ],
    "devDependencies": {
        "@babel/cli": "^7.12.10",
        "@babel/core": "^7.12.10",
        "@babel/preset-env": "^7.12.11",
        "chai": "^4.2.0",
        "clean-webpack-plugin": "^3.0.0",
        "coveralls": "^3.1.0",
        "eslint": "^7.15.0",
        "jsdom": "^16.4.0",
        "mocha": "^8.2.1",
        "mocha-lcov-reporter": "^1.3.0",
        "nyc": "^15.1.0",
        "webpack": "^5.11.0",
        "webpack-cli": "^4.2.0",
        "webpack-merge": "^5.7.2"
    },
    "engines": {
        "node": ">= 10.0"
    }
}
